# ================================
# Netlify Build Configuration
# ================================
[build]
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.9.0"
  NPM_VERSION = "10.1.0"
  NEXT_TELEMETRY_DISABLED = "1"
  CI = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = true

# ================================
# Security Headers (CSP, XSS, etc.)
# ================================
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' 'wasm-unsafe-eval';
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https:;
      connect-src 'self' https://*.firebaseio.com https://*.firebaseapp.com https://your-api-domain.com;
      frame-src 'self';
      object-src 'none';
    """

# ================================
# Redirects
# ================================
# Let the Netlify Next.js plugin handle routing and asset serving.
# Previously a catch-all redirect to /index.html caused _next static
# assets to be returned incorrectly (wrong MIME / 404). Removing these
# redirects fixes that. If you need custom redirects, add specific
# rules that don't conflict with Next.js output paths.

# ================================
# Cache Headers for Next.js Static Assets
# ================================
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/image/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
